### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by CosimoRusso** [simonestaffa/tis-notes#1]
List of typos in the form (line, word, replacement):

https://github.com/simonestaffa/tis-notes/blob/ae08c679a6697951a1c7f2c4ed5d34cf9eef006d/tis-notes.tex#L93 _dervies_ / _derives_.

https://github.com/simonestaffa/tis-notes/blob/ae08c679a6697951a1c7f2c4ed5d34cf9eef006d/tis-notes.tex#L189 _ad_ / _as_

https://github.com/simonestaffa/tis-notes/blob/ae08c679a6697951a1c7f2c4ed5d34cf9eef006d/tis-notes.tex#L203  _it_ / _if_

https://github.com/simonestaffa/tis-notes/blob/ae08c679a6697951a1c7f2c4ed5d34cf9eef006d/tis-notes.tex#L280 _just if_ / _as if_

https://github.com/simonestaffa/tis-notes/blob/ae08c679a6697951a1c7f2c4ed5d34cf9eef006d/tis-notes.tex#L333 _an_ / _and_

https://github.com/simonestaffa/tis-notes/blob/ae08c679a6697951a1c7f2c4ed5d34cf9eef006d/tis-notes.tex#L361 _semantics_ / _semantic_

https://github.com/simonestaffa/tis-notes/blob/ae08c679a6697951a1c7f2c4ed5d34cf9eef006d/tis-notes.tex#L474 _ad_ / _as_

https://github.com/simonestaffa/tis-notes/blob/ae08c679a6697951a1c7f2c4ed5d34cf9eef006d/tis-notes.tex#L492 _in_ / _is_

https://github.com/simonestaffa/tis-notes/blob/ae08c679a6697951a1c7f2c4ed5d34cf9eef006d/tis-notes.tex#L558 _ss_ / _?_

https://github.com/simonestaffa/tis-notes/blob/ae08c679a6697951a1c7f2c4ed5d34cf9eef006d/tis-notes.tex#L619  the arrow is not shown correctly in the pdf

https://github.com/simonestaffa/tis-notes/blob/ae08c679a6697951a1c7f2c4ed5d34cf9eef006d/tis-notes.tex#695 _structured_ / _structure_

**Comment by limone-eth** [comment]
Thanks @CosimoRusso, I've just uploaded a new version of the document!
